Repository sqm-autorate/sqm-autorate, pull requests merged in 2022-01, with the labels that each got.

#44 more advanced settings
  README.md
  lib/sqm-autorate.lua
Labels: documentation, enhancement

#46 Develop/add timestamps
  lib/sqm-autorate.lua
Labels: enhancement

#49 Make speed increase step a percentage of base speed
  lib/sqm-autorate.lua
Labels: enhancement

#52 Develop/choose reflectors gently
  .gitignore
  README.md
  lib/sqm-autorate.lua
  sqm-autorate-setup.sh
Labels: enhancement

#50 Help end user to understand reflectors baseline values
  lib/sqm-autorate.lua
Labels: enhancement

#42 Add additional ICMP reflectors
  lib/sqm-autorate.lua
Labels: enhancement

#53 Major development update. Ready to proceed to public testing.
  .gitignore
  README.md
  lib/reflectors-icmp.csv
  lib/reflectors-udp.csv
  lib/sqm-autorate.lua
  service/sqm-autorate.service
  sqm-autorate-remove.sh
  sqm-autorate-setup.sh
Labels: enhancement

#55 Strong editorial pass over the README.md file
  README.md
  lib/getstats.sh
Labels: documentation, enhancement

#57 Develop/main
  README.md
  lib/getstats.sh
  lib/sqm-autorate.lua
  sqm-autorate-setup.sh
Labels: bug, documentation

#59 Update README.md
  README.md
Labels: documentation, enhancement

#66 Removed all IPv6 reflectors and added over 100 more IPv4 reflectors.
  lib/reflectors-icmp.csv
Labels: enhancement

#62 Add step to clean up autorate files from /tmp
  sqm-autorate-remove.sh
Labels: enhancement

#63 Develop/softstart
  lib/sqm-autorate.lua
Labels: enhancement

#68 just do the math for the exponential weighted average factors. so it …
  lib/sqm-autorate.lua
Labels: enhancement

#69 Develop/juliavis
  julia/datavis.html
  julia/ewmavis.jl
  julia/plotstats.jl
Labels: documentation, enhancement

#67 re-organise and rename config options
  README.md
  config/sqm-autorate.config
  lib/sqm-autorate.lua
  sqm-autorate-setup.sh
Labels: documentation, enhancement

#70 Version 0.4.0 Release
  README.md
  config/sqm-autorate.config
  julia/datavis.html
  julia/ewmavis.jl
  julia/plotstats.jl
  lib/sqm-autorate.lua
  sqm-autorate-remove.sh
  sqm-autorate-setup.sh
Labels: documentation, enhancement

#79 Develop/softstart
  lib/sqm-autorate.lua
Labels: bug, enhancement

#80 Version 0.4.2 Release
  lib/sqm-autorate.lua
Labels: bug, enhancement

#84 Fix rollover issue
  lib/sqm-autorate.lua
Labels: bug

#89 Develop/main
  lib/sqm-autorate.lua
Labels: bug

#96 Attempt at br-lan fix.
  lib/sqm-autorate.lua
Labels: bug

#92 Add more reflectors in APAC region
  lib/reflectors-icmp.csv
Labels: enhancement, good first issue

#100 Closes Missing curl command when running setup Fail-Safe/sqm-autorate#93
  sqm-autorate-setup.sh
Labels: bug

#111 Fix for GH issue #99 per @jeverley. Closes #99.
  lib/sqm-autorate.lua
Labels: bug

#113 edit and re-organise the README
  README.md
Labels: documentation

#123 Modularisation stage 2 - settings
  lib/sqm-autorate.lua
  lib/sqma-settings.lua
Labels: enhancement

#72 improved language and layout in julia/datavis.html
  julia/datavis.html
Labels: documentation

#118 WAN interface takedown tx/rx stats file handling bug fix (issue #101, 105)
  lib/sqm-autorate.lua
Labels: bug
